#ifndef CAI_CONFIG_H
#define CAI_CONFIG_H


#include <math.h>
#include <raylib.h>


#define DEF_FONT_FILE "resources/font/cascadia.ttf"
#define DEF_FONT_SIZE 20
#define DEF_SAVE_FILE "neuralnetwork.data"
#define DEF_SAVE_FILE_NAME_LEN (256)

#define DEF_WIN_WIDTH 1080
#define DEF_WIN_HEIGHT 720



#define DEF_VALUEBOX_WIDTH 3
#define DEF_VALUEBOX_HEIGHT 1

#define DEF_ROAD_WIDTH ((double)DEF_WIN_WIDTH / 4)
#define DEF_ROAD_DASHLEN 30
#define DEF_ROAD_DASHWIDTH 5
#define DEF_ROAD_LANES 3
#define DEF_ROAD_COLOR GRAY
#define DEF_ROAD_DASHCOLOR RAYWHITE
#define DEF_ROAD_LANEWIDTH ((double)DEF_ROAD_WIDTH / (double)DEF_ROAD_LANES - DEF_ROAD_DASHWIDTH)



#define DISTANCE_FACTOR 10
#define DEF_ASPECT_RATIO ((double)DEF_WIN_HEIGHT / DEF_WIN_WIDTH)

#define DEF_TRAFFIC_COUNT 4
#define DEF_TRAFFIC_SPD (25*1.6f) /* 30 mph */
#define DEF_TRAFFIC_COLOR RED
#define TRAFFIC_BOTTOM (2.f * DEF_ASPECT_RATIO)
#define TRAFFIC_TOP (-2.f * DEF_ASPECT_RATIO)
#define TRAFFIC_NEXT -(((double)DEF_ROAD_LANES - 1) / DEF_TRAFFIC_COUNT)


#define DEF_CAR_FRICTION .090f
#define DEF_CAR_ANGLETURN 180.0f
#define DEF_CAR_ACCEL 25.0f
#define DEF_CAR_DECEL (DEF_CAR_ACCEL * 3)
#define DEF_CAR_MAX_REVERSE 20.0f
#define DEF_CAR_MAX_SPEED (70*1.6)

#define DEF_CAR_COLOR DARKBLUE

#define DEF_CAR_WIDTH ((double)DEF_ROAD_LANEWIDTH * 5/8)
#define DEF_CAR_LEN (DEF_CAR_WIDTH * 7/4)

#define DEF_CAR_RECT(arg_x, arg_y) \
    (Rectangle){.x = arg_x, .y = arg_y, \
        .width = DEF_CAR_WIDTH, .height = DEF_CAR_LEN}
#define DEF_CAR_POLYCOUNT 4



#define DEF_SENSOR_RAYLEN (250.0f)
#define DEF_SENSOR_RAYSPREAD (60)
#define DEF_SENSOR_COLORTOUCHED BLACK
#define DEF_SENSOR_COLORNORMAL YELLOW
#define DEF_SENSOR_RAYCOUNT 7


#define DEF_NN_ARCH_SIZE 2
#define DEF_NN_ARCH_LEVELS (usize_t[DEF_NN_ARCH_SIZE]){DEF_SENSOR_RAYCOUNT, 4}
#define DEF_KILL_THRESHOLD TRAFFIC_BOTTOM

#define DEF_LEVEL_NODE_RADIUS 20.f


#endif /* CAI_CONFIG_H */

